"""Seed list: Growth Equity Interview Guide 'Top 18 Technology Private Equity Firms'.

Source: https://growthequityinterviewguide.com/private-equity/private-equity-primer/technology-private-equity-firms
The article is subjective (not AUM-ranked). Featured firms are listed by HQ city;
honorable mentions sit under those city sections. Mega-funds (Blackstone, KKR, Carlyle)
invest well beyond software — keep `multi_sector` when filtering a tech-only TAM.
"""

from __future__ import annotations

SEED_SOURCE_URL = (
    "https://growthequityinterviewguide.com/private-equity/"
    "private-equity-primer/technology-private-equity-firms"
)

# Vitruvian's site is client-rendered. These names are repeatedly cited in
# public coverage of the firm (Wikipedia + 2025–2026 deal announcements).
VITRUVIAN_PUBLIC_HOLDINGS = [
    "Addepar",
    "Africa Specialty Risks",
    "AlphaSense",
    "Aquabyte",
    "Aspia",
    "Cato Networks",
    "DeepIntent",
    "Dojo",
    "Hinge Health",
    "Klook",
    "Marqeta",
    "Moonfare",
    "OAG",
    "Options Technology",
    "Pine Labs",
    "Skyscanner",
    "Thunes",
    "Twinkl",
]

# Select investments named in the article (and its success-story section).
# Used as a fallback so named examples survive even if a live scrape is blocked.
ARTICLE_SELECT_INVESTMENTS = {
    "silver-lake": [
        "Dell Technologies",
        "BYJU's",
        "GoDaddy",
        "Airbnb",
        "Ant Group",
    ],
    "accel-kkr": ["Pegasus", "Salary.com", "Recurly"],
    "hellman-friedman": [
        "Formula One",
        "Nasdaq",
        "Checkmarx",
        "Mondrian",
        "Scout24",
    ],
    "vista-equity": [
        "AppFolio",
        "Web.com",
        "Infoblox",
        "Solera Holdings",
        "Cvent",
        "Marketo",
    ],
    "thoma-bravo": ["SolarWinds"],
    "providence-equity": [
        "TenStreet",
        "Seesaw",
        "Smartly.io",
        "RentPath",
        "Warner Music Group",
        "Blackboard",
        "Bresnan Communications",
    ],
    "spectrum-equity": ["Bitly", "customer.io", "GoodRx"],
    "warburg-pincus": ["BEA Systems", "Neustar", "CrowdStrike", "Avalara"],
    "wcas": ["LINQ", "Decision One", "Headstrong"],
    "carlyle": ["Hack the Box", "Abrigo", "Agilox"],
    "permira": ["McAfee", "GoCardless", "Genesys", "Fullstory"],
    "platinum-equity": ["Solenis", "McGraw Hill", "Urbaser"],
}

FIRMS: list[dict] = [
    {
        "firm_id": "silver-lake",
        "name": "Silver Lake",
        "hq_city": "San Mateo",
        "hq_region": "San Francisco Bay Area",
        "list_role": "featured",
        "multi_sector": False,
        "website": "https://www.silverlake.com/",
        "portfolio_url": "https://www.silverlake.com/portfolio/",
        "wiki_category": "Silver Lake (investment firm) companies",
        "adapter": "silver_lake",
    },
    {
        "firm_id": "accel-kkr",
        "name": "Accel-KKR",
        "hq_city": "Menlo Park",
        "hq_region": "San Francisco Bay Area",
        "list_role": "featured",
        "multi_sector": False,
        "website": "https://www.accel-kkr.com/",
        "portfolio_url": "https://www.accel-kkr.com/portfolio/",
        "wiki_category": None,
        "adapter": "accel_kkr",
    },
    {
        "firm_id": "hellman-friedman",
        "name": "Hellman & Friedman",
        "hq_city": "San Francisco",
        "hq_region": "San Francisco Bay Area",
        "list_role": "featured",
        "multi_sector": False,
        "website": "https://hf.com/",
        "portfolio_url": "https://hf.com/portfolio/",
        "wiki_category": "Hellman & Friedman companies",
        "adapter": "hellman_friedman",
    },
    {
        "firm_id": "francisco-partners",
        "name": "Francisco Partners",
        "hq_city": "San Francisco",
        "hq_region": "San Francisco Bay Area",
        "list_role": "honorable_mention",
        "multi_sector": False,
        "website": "https://www.franciscopartners.com/",
        "portfolio_url": "https://www.franciscopartners.com/investments",
        "wiki_category": None,
        "adapter": "francisco_partners",
    },
    {
        "firm_id": "genstar-capital",
        "name": "Genstar Capital",
        "hq_city": "San Francisco",
        "hq_region": "San Francisco Bay Area",
        "list_role": "honorable_mention",
        "multi_sector": True,
        "website": "https://www.gencap.com/",
        "portfolio_url": "https://www.gencap.com/companies/",
        "wiki_category": None,
        "adapter": "genstar",
    },
    {
        "firm_id": "vista-equity",
        "name": "Vista Equity Partners",
        "hq_city": "Austin",
        "hq_region": "Texas",
        "list_role": "featured",
        "multi_sector": False,
        "website": "https://www.vistaequitypartners.com/",
        "portfolio_url": "https://www.vistaequitypartners.com/about/companies/",
        "wiki_category": "Vista Equity Partners companies",
        "adapter": "vista",
    },
    {
        "firm_id": "thoma-bravo",
        "name": "Thoma Bravo",
        "hq_city": "Chicago",
        "hq_region": "Chicago",
        "list_role": "featured",
        "multi_sector": False,
        "website": "https://www.thomabravo.com/",
        "portfolio_url": "https://www.thomabravo.com/portfolio",
        "wiki_category": "Thoma Bravo companies",
        "adapter": "thoma_bravo",
    },
    {
        "firm_id": "providence-equity",
        "name": "Providence Equity Partners",
        "hq_city": "Providence",
        "hq_region": "Boston area",
        "list_role": "featured",
        "multi_sector": True,
        "website": "https://www.provequity.com/",
        "portfolio_url": "https://www.provequity.com/portfolio",
        "wiki_category": "Providence Equity Partners companies",
        "adapter": "providence",
    },
    {
        "firm_id": "spectrum-equity",
        "name": "Spectrum Equity",
        "hq_city": "Boston",
        "hq_region": "Boston",
        "list_role": "featured",
        "multi_sector": False,
        "website": "https://www.spectrumequity.com/",
        "portfolio_url": "https://www.spectrumequity.com/portfolio",
        "wiki_category": None,
        "adapter": "spectrum",
    },
    {
        "firm_id": "warburg-pincus",
        "name": "Warburg Pincus",
        "hq_city": "New York",
        "hq_region": "New York",
        "list_role": "featured",
        "multi_sector": True,
        "website": "https://www.warburgpincus.com/",
        "portfolio_url": "https://www.warburgpincus.com/investments/",
        "wiki_category": "Warburg Pincus companies",
        "adapter": "warburg",
    },
    {
        "firm_id": "wcas",
        "name": "Welsh, Carson, Anderson & Stowe",
        "hq_city": "New York",
        "hq_region": "New York",
        "list_role": "featured",
        "multi_sector": True,
        "website": "https://wcas.com/",
        "portfolio_url": "https://wcas.com/firm/investments/",
        "wiki_category": None,
        "adapter": "wcas",
    },
    {
        "firm_id": "blackstone",
        "name": "Blackstone",
        "hq_city": "New York",
        "hq_region": "New York",
        "list_role": "honorable_mention",
        "multi_sector": True,
        "website": "https://www.blackstone.com/",
        "portfolio_url": "https://www.blackstone.com/",
        "wiki_category": "Blackstone Inc. companies",
        "adapter": "wikipedia_only",
    },
    {
        "firm_id": "kkr",
        "name": "KKR",
        "hq_city": "New York",
        "hq_region": "New York",
        "list_role": "honorable_mention",
        "multi_sector": True,
        "website": "https://www.kkr.com/",
        "portfolio_url": "https://www.kkr.com/",
        "wiki_category": "KKR & Co. companies",
        "adapter": "wikipedia_only",
    },
    {
        "firm_id": "carlyle",
        "name": "Carlyle",
        "hq_city": "Washington, D.C.",
        "hq_region": "Washington DC",
        "list_role": "featured",
        "multi_sector": True,
        "website": "https://www.carlyle.com/",
        "portfolio_url": "https://www.carlyle.com/",
        "wiki_category": "The Carlyle Group companies",
        "adapter": "wikipedia_only",
    },
    {
        "firm_id": "permira",
        "name": "Permira",
        "hq_city": "London",
        "hq_region": "London",
        "list_role": "featured",
        "multi_sector": True,
        "website": "https://www.permira.com/",
        "portfolio_url": "https://www.permira.com/portfolio/our-portfolio",
        "wiki_category": "Permira companies",
        "adapter": "permira",
    },
    {
        "firm_id": "vitruvian",
        "name": "Vitruvian Partners",
        "hq_city": "London",
        "hq_region": "London",
        "list_role": "honorable_mention",
        "multi_sector": False,
        "website": "https://www.vitruvianpartners.com/",
        "portfolio_url": "https://www.vitruvianpartners.com/investments",
        "wiki_category": None,
        "adapter": "vitruvian",
    },
    {
        "firm_id": "hg",
        "name": "Hg",
        "hq_city": "London",
        "hq_region": "London",
        "list_role": "honorable_mention",
        "multi_sector": False,
        "website": "https://hgcapital.com/",
        "portfolio_url": "https://hgcapital.com/portfolio",
        "wiki_category": None,
        "adapter": "hg",
    },
    {
        "firm_id": "platinum-equity",
        "name": "Platinum Equity",
        "hq_city": "Beverly Hills",
        "hq_region": "Los Angeles",
        "list_role": "featured",
        "multi_sector": True,
        "website": "https://www.platinumequity.com/",
        "portfolio_url": "https://www.platinumequity.com/our-companies/",
        "wiki_category": None,
        "adapter": "platinum",
    },
]
